variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  stage: build
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --update --no-cache rsync openssh-client
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo ${SSH_PRIVATE_KEY} > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa ec2-18-159-99-126.eu-central-1.compute.amazonaws.com >> ~/.ssh/known_hosts
  script:
    - rsync -az --delete public/ updator@ec2-18-159-99-126.eu-central-1.compute.amazonaws.com:/var/www/template
  only:
    - master


## Reference: https://softwareadept.xyz/2020/06/deploying-hugo-with-gitlab-ci/
