backend:
    #name: test-repo
    name: gitlab
    repo: CIBMarketing/cib_netlifycms
    auth_type: implicit
    app_id: 94ea9594f41aa31e2764213529b1bed6d1c3dbdaa6440d2ca0c7cbcc4e4b1019
media_folder: static/images/karriere
public_folder: /images
collections:
  - name: 'karriere'
    label: 'Karriere'
    folder: content/karriere
    extension: md
    format: json-frontmatter
    identifier_field: Title
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
        preview: true
    fields:
      - { label: 'Title', name: 'Title', widget: 'string' }
      - { label: 'Translation key', name: 'translationKey', widget: 'string' }
      - { name: 'type', default: "karriere", widget: "hidden" }
      - label: "Header"
        name: "header"
        widget: "object"
        fields:
          - { label: 'Titel', name: 'Titel', widget: 'string' }
          - { label: 'Button', name: 'Button', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'string' }
      - label: "Button"
        name: "Button"
        widget: "object"
        fields:
          - { label: 'Senden', name: 'Senden', widget: 'string' }
          - { label: 'Anfragen', name: 'Anfragen', widget: 'string' }
      - { label: 'NoShow', name: 'NoShowButton', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Filter menu"
        name: "Filtermenu"
        widget: "object"
        fields:
          - { label: "All", name: "All", widget: 'string', default: "Alle" }
          - { label: "Items", name: "Items", widget: 'list' }